version: '2'

services:
  nginx-proxy:
    image: docker-registry.ingotcloud.top/nginxproxy/nginx-proxy:1.8
    container_name: nginx-proxy
    restart: always
    networks:
      - extnet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /ingot-data/docker/volumes/nginx-proxy/conf:/etc/nginx/conf.d
      - /ingot-data/docker/volumes/nginx-proxy/vhost:/etc/nginx/vhost.d
      - /ingot-data/docker/volumes/nginx-proxy/html:/usr/share/nginx/html
      - /ingot-data/docker/volumes/nginx-proxy/dhparam:/etc/nginx/dhparam
      - /ingot-data/docker/volumes/nginx-proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro


  acme-companion:
    image: docker-registry.ingotcloud.top/nginxproxy/acme-companion:2.6
    container_name: nginx-proxy-acme
    restart: always
    networks:
      - extnet
    volumes_from:
      - nginx-proxy
    volumes:
      - /ingot-data/docker/volumes/nginx-proxy/certs:/etc/nginx/certs:rw
      - /ingot-data/docker/volumes/nginx-proxy/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  extnet:
    name: ingot-net
    external: true
