#!/usr/bin/env bash

source ./.env

CLUSTER_BROKER1_VOLUME=${WORK_DIR}/${CLUSTER_BROKER1_NAME}/volumes
CLUSTER_BROKER2_VOLUME=${WORK_DIR}/${CLUSTER_BROKER2_NAME}/volumes
CLUSTER_BROKER3_VOLUME=${WORK_DIR}/${CLUSTER_BROKER3_NAME}/volumes

# 给 Kafka 用户赋权限, 注意UID和GID，这里用的是1000
mkdir -p ${CLUSTER_BROKER1_VOLUME}
chown -R 1000:1000 ${CLUSTER_BROKER1_VOLUME}
chmod -R 755 ${CLUSTER_BROKER1_VOLUME}

mkdir -p ${CLUSTER_BROKER2_VOLUME}
chown -R 1000:1000 ${CLUSTER_BROKER2_VOLUME}
chmod -R 755 ${CLUSTER_BROKER2_VOLUME}

mkdir -p ${CLUSTER_BROKER3_VOLUME}
chown -R 1000:1000 ${CLUSTER_BROKER3_VOLUME}
chmod -R 755 ${CLUSTER_BROKER3_VOLUME}

docker compose up -d