#!/usr/bin/env bash

source ./env/standalone.env

mkdir -p ${NACOS_VOLUME_ROOT}/logs

docker run --name nacos-server \
  --network ingot-net \
  --restart always \
  -p 8181:8080 \
  -p 8848:8848 \
  -p 9848:9848 \
  -e MODE=${MODE} \
  -e NACOS_SERVER_PORT=${NACOS_SERVER_PORT} \
  -e SPRING_DATASOURCE_PLATFORM=${SPRING_DATASOURCE_PLATFORM} \
  -e MYSQL_SERVICE_HOST=${MYSQL_SERVICE_HOST} \
  -e MYSQL_SERVICE_DB_NAME=${MYSQL_SERVICE_DB_NAME} \
  -e MYSQL_SERVICE_PORT=${MYSQL_SERVICE_PORT} \
  -e MYSQL_SERVICE_USER=${MYSQL_SERVICE_USER} \
  -e MYSQL_SERVICE_PASSWORD=${MYSQL_SERVICE_PASSWORD} \
  -e MYSQL_SERVICE_DB_PARAM=${MYSQL_SERVICE_DB_PARAM} \
  -e NACOS_AUTH_ENABLE=${NACOS_AUTH_ENABLE} \
  -e NACOS_AUTH_SYSTEM_TYPE=${NACOS_AUTH_SYSTEM_TYPE} \
  -e NACOS_AUTH_TOKEN_EXPIRE_SECONDS=${NACOS_AUTH_TOKEN_EXPIRE_SECONDS} \
  -e NACOS_AUTH_TOKEN=${NACOS_AUTH_TOKEN} \
  -e NACOS_AUTH_IDENTITY_KEY=${NACOS_AUTH_IDENTITY_KEY} \
  -e NACOS_AUTH_IDENTITY_VALUE=${NACOS_AUTH_IDENTITY_VALUE} \
  -v ${NACOS_VOLUME_ROOT}/logs:/home/nacos/logs \
  -d nacos/nacos-server:${NACOS_VERSION}
