services:
  dns:
    image: docker-registry.ingotcloud.top/technitium/dns-server:15.2.0
    container_name: technitium-dns
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "5380:5380/tcp"
    volumes:
      - /data/docker-volumes/dns:/etc/dns
    environment:
      - DNS_SERVER_DOMAIN=dns.wande.local
      - DNS_SERVER_ADMIN_PASSWORD=Wddz@2190388