services:
  nacos1:
    hostname: ${NACOS1_HOSTNAME}
    container_name: ${NACOS1_CONTEINER_NAME}
    image: ${NACOS_IMAGE}:${NACOS_VERSION}
    networks:
      - extnet
    volumes:
      - ${WORK_DIR}/${NACOS1_CONTEINER_NAME}/volumes/logs:/home/nacos/logs
    ports:
      - "${NACOS1_CONSOLE_PORT}:8080"
      - "${NACOS1_SERVER_PORT}:8848"
      - "${NACOS1_GRPC_CLIENT_PORT}:9848"
      - "${NACOS1_GRPC_SERVER_PORT}:9849"
    environment:
      - MODE=${MODE}
      - PREFER_HOST_MODE=${PREFER_HOST_MODE}
      - NACOS_SERVERS=${NACOS_SERVERS}
      - NACOS_SERVER_PORT=${NACOS1_SERVER_PORT}
      - SPRING_DATASOURCE_PLATFORM=${SPRING_DATASOURCE_PLATFORM}
      - MYSQL_SERVICE_HOST=${MYSQL_SERVICE_HOST}
      - MYSQL_SERVICE_DB_NAME=${MYSQL_SERVICE_DB_NAME}
      - MYSQL_SERVICE_PORT=${MYSQL_SERVICE_PORT}
      - MYSQL_SERVICE_USER=${MYSQL_SERVICE_USER}
      - MYSQL_SERVICE_PASSWORD=${MYSQL_SERVICE_PASSWORD}
      - MYSQL_SERVICE_DB_PARAM=${MYSQL_SERVICE_DB_PARAM}
      - NACOS_AUTH_ENABLE=${NACOS_AUTH_ENABLE}
      - NACOS_AUTH_SYSTEM_TYPE=${NACOS_AUTH_SYSTEM_TYPE}
      - NACOS_AUTH_TOKEN_EXPIRE_SECONDS=${NACOS_AUTH_TOKEN_EXPIRE_SECONDS}
      - NACOS_AUTH_TOKEN=${NACOS_AUTH_TOKEN}
      - NACOS_AUTH_IDENTITY_KEY=${NACOS_AUTH_IDENTITY_KEY}
      - NACOS_AUTH_IDENTITY_VALUE=${NACOS_AUTH_IDENTITY_VALUE}
    restart: always

  nacos2:
    hostname: ${NACOS2_HOSTNAME}
    container_name: ${NACOS2_CONTEINER_NAME}
    image: ${NACOS_IMAGE}:${NACOS_VERSION}
    networks:
      - extnet
    volumes:
      - ${WORK_DIR}/${NACOS2_CONTEINER_NAME}/volumes/logs:/home/nacos/logs
    ports:
      - "${NACOS2_CONSOLE_PORT}:8080"
      - "${NACOS2_SERVER_PORT}:8848"
      - "${NACOS2_GRPC_CLIENT_PORT}:9848"
      - "${NACOS2_GRPC_SERVER_PORT}:9849"
    environment:
      - MODE=${MODE}
      - PREFER_HOST_MODE=${PREFER_HOST_MODE}
      - NACOS_SERVERS=${NACOS_SERVERS}
      - NACOS_SERVER_PORT=${NACOS2_SERVER_PORT}
      - SPRING_DATASOURCE_PLATFORM=${SPRING_DATASOURCE_PLATFORM}
      - MYSQL_SERVICE_HOST=${MYSQL_SERVICE_HOST}
      - MYSQL_SERVICE_DB_NAME=${MYSQL_SERVICE_DB_NAME}
      - MYSQL_SERVICE_PORT=${MYSQL_SERVICE_PORT}
      - MYSQL_SERVICE_USER=${MYSQL_SERVICE_USER}
      - MYSQL_SERVICE_PASSWORD=${MYSQL_SERVICE_PASSWORD}
      - MYSQL_SERVICE_DB_PARAM=${MYSQL_SERVICE_DB_PARAM}
      - NACOS_AUTH_ENABLE=${NACOS_AUTH_ENABLE}
      - NACOS_AUTH_SYSTEM_TYPE=${NACOS_AUTH_SYSTEM_TYPE}
      - NACOS_AUTH_TOKEN_EXPIRE_SECONDS=${NACOS_AUTH_TOKEN_EXPIRE_SECONDS}
      - NACOS_AUTH_TOKEN=${NACOS_AUTH_TOKEN}
      - NACOS_AUTH_IDENTITY_KEY=${NACOS_AUTH_IDENTITY_KEY}
      - NACOS_AUTH_IDENTITY_VALUE=${NACOS_AUTH_IDENTITY_VALUE}
    restart: always

  nacos3:
    hostname: ${NACOS3_HOSTNAME}
    container_name: ${NACOS3_CONTEINER_NAME}
    image: ${NACOS_IMAGE}:${NACOS_VERSION}
    networks:
      - extnet
    volumes:
      - ${WORK_DIR}/${NACOS3_CONTEINER_NAME}/volumes/logs:/home/nacos/logs
    ports:
      - "${NACOS3_CONSOLE_PORT}:8080"
      - "${NACOS3_SERVER_PORT}:8848"
      - "${NACOS3_GRPC_CLIENT_PORT}:9848"
      - "${NACOS3_GRPC_SERVER_PORT}:9849"
    environment:
      - MODE=${MODE}
      - PREFER_HOST_MODE=${PREFER_HOST_MODE}
      - NACOS_SERVERS=${NACOS_SERVERS}
      - NACOS_SERVER_PORT=${NACOS3_SERVER_PORT}
      - SPRING_DATASOURCE_PLATFORM=${SPRING_DATASOURCE_PLATFORM}
      - MYSQL_SERVICE_HOST=${MYSQL_SERVICE_HOST}
      - MYSQL_SERVICE_DB_NAME=${MYSQL_SERVICE_DB_NAME}
      - MYSQL_SERVICE_PORT=${MYSQL_SERVICE_PORT}
      - MYSQL_SERVICE_USER=${MYSQL_SERVICE_USER}
      - MYSQL_SERVICE_PASSWORD=${MYSQL_SERVICE_PASSWORD}
      - MYSQL_SERVICE_DB_PARAM=${MYSQL_SERVICE_DB_PARAM}
      - NACOS_AUTH_ENABLE=${NACOS_AUTH_ENABLE}
      - NACOS_AUTH_SYSTEM_TYPE=${NACOS_AUTH_SYSTEM_TYPE}
      - NACOS_AUTH_TOKEN_EXPIRE_SECONDS=${NACOS_AUTH_TOKEN_EXPIRE_SECONDS}
      - NACOS_AUTH_TOKEN=${NACOS_AUTH_TOKEN}
      - NACOS_AUTH_IDENTITY_KEY=${NACOS_AUTH_IDENTITY_KEY}
      - NACOS_AUTH_IDENTITY_VALUE=${NACOS_AUTH_IDENTITY_VALUE}
    restart: always

networks:
  extnet:
    name: ${DOCKER_NETWORK}
    external: true
